language: node_js
node_js:
  - 0.12.2
git:
  depth: 10
cache: # Caching is only supported for private projects.
  directories:
  - ./node_modules
  - ./libraries
  - $HOME/.rvm/gems
before_script:
  - bundle install
  - ./node_modules/.bin/bower install
script:
  - ./node_modules/.bin/gulp build
after_success:
  - ./node_modules/.bin/gulp script:test:report
notifications:
  email: false
before_deploy:
  - ./node_modules/.bin/gulp clean:deploy
deploy:
  provider: heroku
  app: voxel-rsr
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
  api_key:
    secure: XAemIoqrqGp7Q+sWkr1Ny8s7ty0NKcRL6whA6/yTZvQORiCKbWoN3aQSUvhRG37QqRfMQHkW5xZebVF6KEdKcCgqlE3l4L2CXyTvdSQp6Q87C2XeH4PRGa4J9ku9RkL4zM6msHM3lEiXyOjvkgcTvBL2IMhDq/VNo9EZIf0fbtTCV7XHDdINGs0DGmMAOCDg0ErkoF6HpGlxIXbgfDyvJVa+p2vm5BKphdOv9zn/lLWxrIw+IMviqtc8k3TQ1ONWyckpk22FstFKCwSEK0axyDh+C9AWfFqqyecNX6kQ7KPahAcC36IMh5rm5g9rosvL80AdDYojhtQgKyPDpKyTapfFg8/w4/Lvmrr30tOHn8mZzuJcSc4RuNj3NFkJOs3QlOqg7aV6xCFYe2zbV8cB7MRsz+ysSbvdIsOfoU7McezuwKppzYLhA2sOZ0Rm7lwQu7an0OPowQs6bQ5e8esbW4f6yrUWIhbnOg57BIjXaug85kgDK1gQRJL8GvOD/6FN8e3zLMQlOMFKKhFX61Kwuk5QmPldrkmq93fgBLNsKtZZB6fec8ntDITbewVu0XK3zjcGYLVu8ssOJNXmQWOLlV5eXAU+h/BOR2ta01N/ycEpg7NUOz7qCCcyL02pOqW6TMJgoxHluhEZ/KUn2pPXnsNHmmY/2AX0uEMCP2YERNA=
